version: 2

models:
  - name: stg_posts_questions
    description: "Simplified version of the raw posts_questions table."
    columns:
      - name: question_id
        description: "Unique identifier of the question."
        tests:
          - not_null
          - unique
      - name: tags_arr
        description: "Tags applied to the question, split by |."
        tests:
          - dbt_utils.expression_is_true:
              expression: "ARRAY_LENGTH(tags_arr) IS NOT NULL" # test for being an array
      - name: answer_count
        description: "Number of answers given to the question."
      - name: accepted_answer_id
        description: "Indicates the accepted answer (null if no answer has been accepted)."
      - name: view_count
        description: "Number of times the post has been viewed by users."
      - name: score
        description: "Positive votes minus negative votes given to the post by users."
      - name: creation_date
        description: "Timestamp indicating when the answer was posted."
  

  - name: stg_posts_answers
    description: "Simplified version of the raw posts_answers table."
    columns:
      - name: answer_id
        description: "Unique identifier of the answer."
        tests:
          - not_null
          - unique
      - name: parent_id
        description: "Unique identifier of the parent question."
        tests:
          - not_null
      - name: score
        description: "Positive votes minus negative votes given to the post by users."
      - name: creation_date
        description: "Timestamp indicating when the answer was posted."